package school.management.ui;

import java.awt.HeadlessException;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import school.management.Alert;
import school.management.Students;
import school.management.StudentsController;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import org.apache.log4j.Logger;
import school.management.InputException;

/**
 *
 * @author ahmed
 */
public class Add_EditStudentUI extends javax.swing.JFrame {

    private String imagePath="";
    public Add_EditStudentUI() {
        initComponents();
        
        //Create header of the frame
        Header header = new Header(this,jPanel1);
        header.setTitle("Students","icons\\icons8_Student_Registration_100px.png");
        
        this.setTitle("Add new student");
        
        //Make static Calendar
        String[] days =  new String[30];
        String[] years = new String[20];
        String[] months = {"January","February","March","April","May","June","July","August","September","October","November","December"};
        
        for(Integer i = 0; i < 30; i++) {
            days[i] = String.valueOf(i+1);
        }

        for(Integer i = 0; i < 20; i++) {
            years[i] = String.valueOf(2025 - (i+1));
        }
        
        birthDay.setModel(new DefaultComboBoxModel(days));
        birthMonth.setModel(new DefaultComboBoxModel(months));
        birthYear.setModel(new DefaultComboBoxModel(years));
        admissionDay.setModel(new DefaultComboBoxModel(days));
        admissionMonth.setModel(new DefaultComboBoxModel(months));
        admissionYear.setModel(new DefaultComboBoxModel(years));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        std_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        middle_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        stage = new javax.swing.JComboBox();
        update = new javax.swing.JButton();
        birthYear = new javax.swing.JComboBox();
        birthDay = new javax.swing.JComboBox();
        birthMonth = new javax.swing.JComboBox();
        admissionYear = new javax.swing.JComboBox();
        admissionDay = new javax.swing.JComboBox();
        admissionMonth = new javax.swing.JComboBox();
        clear = new javax.swing.JButton();
        add = new javax.swing.JButton();
        close1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        guadian_name = new javax.swing.JTextField();
        photo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        studentPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("ID :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 35));

        std_id.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        std_id.setNextFocusableComponent(first_name);
        std_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                std_idFocusLost(evt);
            }
        });
        jPanel1.add(std_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 250, 35));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("First Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 35));

        first_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        first_name.setNextFocusableComponent(middle_name);
        jPanel1.add(first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 250, 35));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Middle Name :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 35));

        middle_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        middle_name.setNextFocusableComponent(last_name);
        jPanel1.add(middle_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 250, 35));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Last Name :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 35));

        last_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        last_name.setNextFocusableComponent(maleRadio);
        jPanel1.add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 250, 35));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Date of birth :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, 35));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Admission Date :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, 35));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Guadian Name :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, 35));

        phone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 250, 35));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Phone No :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, 35));

        address.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        address.setNextFocusableComponent(stage);
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, 250, 35));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setText("Address :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, 35));

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setText("Gender :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 35));

        maleRadio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(maleRadio);
        maleRadio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        maleRadio.setSelected(true);
        maleRadio.setText("Male");
        maleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioActionPerformed(evt);
            }
        });
        jPanel1.add(maleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, 35));

        femaleRadio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(femaleRadio);
        femaleRadio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        femaleRadio.setText("Female");
        jPanel1.add(femaleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, 35));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Education stages :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, 30));

        stage.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9" }));
        stage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageActionPerformed(evt);
            }
        });
        jPanel1.add(stage, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 130, -1));

        update.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        update.setText("UPDATE");
        update.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        update.setBorderPainted(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 710, 250, 40));

        birthYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(birthYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 90, 35));

        birthDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(birthDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, 35));

        birthMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        birthMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthMonthActionPerformed(evt);
            }
        });
        jPanel1.add(birthMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 90, 35));

        admissionYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(admissionYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 90, 35));

        admissionDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(admissionDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, 35));

        admissionMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(admissionMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 90, 35));

        clear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        clear.setText("Clear Fields");
        clear.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        clear.setBorderPainted(false);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 770, 250, 40));

        add.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        add.setText("ADD");
        add.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        add.setBorderPainted(false);
        add.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 710, 250, 40));

        close1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        close1.setText("CLOSE");
        close1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        close1.setBorderPainted(false);
        close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close1ActionPerformed(evt);
            }
        });
        jPanel1.add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 770, 250, 40));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 10, 500));
        jSeparator1.getAccessibleContext().setAccessibleName("");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Notes :");

        notes.setColumns(20);
        notes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        notes.setRows(5);
        jScrollPane2.setViewportView(notes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 250, 220));

        guadian_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(guadian_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 250, 35));

        photo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        photo.setText("ADD PHOTO");
        photo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        photo.setBorderPainted(false);
        photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoActionPerformed(evt);
            }
        });
        jPanel1.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 110, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Photo  :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, 20));

        studentPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentPic.setText("Picture review");
        jPanel1.add(studentPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 250, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Clear all fields
    private void clearFields() {
        address.setText("");
        admissionDay.setSelectedIndex(0);
        admissionMonth.setSelectedIndex(0);
        admissionYear.setSelectedIndex(0);
        birthDay.setSelectedIndex(0);
        birthMonth.setSelectedIndex(0);
        birthYear.setSelectedIndex(0);
        first_name.setText("");
        middle_name.setText("");
        last_name.setText("");
        guadian_name.setText("");
        notes.setText("");
        stage.setSelectedIndex(0);
        phone.setText("");
        std_id.setText("");
        studentPic.setIcon(new javax.swing.ImageIcon(""));
    }
    
    //Get data from all fields and return in students object
    private Students getInputs(){
        try {
            Students s = new Students();
            s.setAddress(address.getText());
            s.setBirthday(birthYear.getSelectedItem() + "-" + (birthMonth.getSelectedIndex() + 1) + "-" + birthDay.getSelectedItem());
            s.setAdmissionDate(admissionYear.getSelectedItem() + "-" + (admissionMonth.getSelectedIndex() + 1) + "-" + admissionDay.getSelectedItem());
            s.setEducationStage(stage.getSelectedIndex() + 1);
            s.setFirstName(first_name.getText());
            if (maleRadio.isSelected() == true) {
                s.setGender(1);
            } else {
                s.setGender(2);
            }
            s.setGuardianName(guadian_name.getText());
            s.setId(Integer.parseInt(std_id.getText()));
            s.setLastName(last_name.getText());
            s.setMiddleName(middle_name.getText());
            s.setNotes(notes.getText());
            s.setPhone(phone.getText());
            return s;
        } catch (Exception ex) {
            Alert.viewErrorMessage("There's an error .. !");
            Logger.getLogger(Add_EditStudentUI.class).error(ex);
        }
        return null;        
    }

    //Get Data from another interface and put it in fields
    protected void setInputs(Students s){
        std_id.setText(s.getId().toString());
        address.setText(s.getAddress());
        
        String[] admission = s.getAdmissionDate().split("-");
        admissionYear.setSelectedItem(admission[0]);
        admissionMonth.setSelectedIndex(Integer.parseInt(admission[1]) - 1);
        admissionDay.setSelectedIndex(Integer.parseInt(admission[2]) - 1);

        String[] birth = s.getBirthday().split("-");
        birthYear.setSelectedItem(birth[0]);
        birthMonth.setSelectedIndex(Integer.parseInt(birth[1]) - 1);
        birthDay.setSelectedIndex(Integer.parseInt(birth[2]) - 1);
        
        first_name.setText(s.getFirstName());
        middle_name.setText(s.getMiddleName());
        last_name.setText(s.getLastName());
        guadian_name.setText(s.getGuardianName());
        notes.setText(s.getNotes());
        stage.setSelectedIndex(s.getEducationStage()-1);
        phone.setText(s.getPhone());
        if (s.getGender() == 1){
            maleRadio.setSelected(true);
        } else {
            femaleRadio.setSelected(true);
        }
        try{
            File check = new File("image\\pp_"+std_id.getText()+".jpg");
            if (check.exists()) {
                studentPic.setIcon(new javax.swing.ImageIcon(check.getAbsolutePath()));
            } else {
                studentPic.setIcon(new javax.swing.ImageIcon("image\\student.png"));
            }
        } catch(Exception ex){
            Alert.viewErrorMessage("There's an error ... !");
            Logger.getLogger(Add_EditStudentUI.class).error(ex);
        }
    }
    
    //Check fields pattren and if any field don't match throw in exception
    private void checkFields() throws InputException {
        if(!std_id.getText().matches("[0-9]{3}[0-9]+")){
            throw new InputException("ID Must be at least 4 numbers\nID");
        }
        if(!first_name.getText().matches("[a-zA-Z]{2}[a-zA-Z]+")){
            throw new InputException("First Name");        
        }
        if(!middle_name.getText().matches("[a-zA-Z]{2}[a-zA-Z]+")){
            throw new InputException("Middle Name");
        }
        if(!last_name.getText().matches("[a-zA-Z]{2}[a-zA-Z]+")){
            throw new InputException("Last Name");
        }
        if(!guadian_name.getText().matches("[a-zA-Z]{2}[a-zA-Z]+\\s*[a-zA-z]+")){
            throw new InputException("Parent Name");
        }
        if(!phone.getText().matches("(2189|09)[1245][0-9]{7}")){
            throw new InputException("Phone");
        }
    }
    
    
    //Add & update student image
    private void addImageToStudent(){
        File check = new File("image");
        if (!check.exists()) {
            check.mkdir();
        }

        check = new File("image\\pp_"+std_id.getText()+".jpg");
        if (check.exists()) {
            check.delete();
        }
        
        //Copy image file to current program folder in images
        BufferedInputStream fis;
        BufferedOutputStream fos;
        try {
            fis = new BufferedInputStream(new FileInputStream(imagePath));
            fos = new BufferedOutputStream(new FileOutputStream("image\\pp_" + std_id.getText()+ ".jpg"));
            int d;
            while ((d = fis.read()) != -1) {
                fos.write(d);
            }
            fis.close();
            fos.close();
        } catch (FileNotFoundException ex){
            Alert.viewWarningMessage("File can't be found");
            Logger.getLogger(Add_EditStudentUI.class).error(ex);
        } catch (IOException ex){
            Alert.viewWarningMessage("There's an error");
            Logger.getLogger(Add_EditStudentUI.class).error(ex);
        }
    }
    
    private void maleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioActionPerformed
        
    }//GEN-LAST:event_maleRadioActionPerformed

    private void stageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageActionPerformed

    }//GEN-LAST:event_stageActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            checkFields();
            StudentsController.update(getInputs());
            if(!imagePath.equals("")){
                addImageToStudent();
            }
            clearFields();
            Alert.viewSuccessMessage("Successfully update student information");
        } catch (InputException ex){
            Alert.viewWarningMessage(ex.toString());
        } catch (Exception ex) {
            Alert.viewErrorMessage("There's an error");
            Logger.getLogger(Add_EditStudentUI.class).error(ex);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clearFields();
    }//GEN-LAST:event_clearActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        try {
            checkFields();
            StudentsController.add(getInputs());
            if(!imagePath.equals("")){
                addImageToStudent();
            }
            clearFields();
            Alert.viewSuccessMessage("Successfully added new student");
            Logger.getLogger(Add_EditStudentUI.class).info("add new student");
        } catch (InputException ex){
            Alert.viewWarningMessage(ex.toString());
        } catch (Exception ex) {
            Alert.viewErrorMessage("There's an error");
            Logger.getLogger(Add_EditStudentUI.class).error(ex);
        }
    }//GEN-LAST:event_addActionPerformed

    private void std_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_std_idFocusLost
        if(std_id.getText().matches("[0-9]+")){
            String id = std_id.getText();
            if (!"".equals(id)) {
                Students s = StudentsController.getStudentByID(std_id.getText());
                if (s != null) {
                    setInputs(s);
                }
            }
        }
    }//GEN-LAST:event_std_idFocusLost

    private void close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_close1ActionPerformed

    private void photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            
            File file = chooser.getSelectedFile();
            imagePath = file.getAbsolutePath();

            //check the image type
            if(!imagePath.contains(".JPEG") && !imagePath.contains(".JPG") && !imagePath.contains(".PNG")
                    && !imagePath.contains(".jpeg") && !imagePath.contains(".jpg") && !imagePath.contains(".png")){
                imagePath = "";
                throw new InputException();
            } else {
                studentPic.setIcon(new javax.swing.ImageIcon(imagePath));
            }
            
        } catch (InputException ex){
            Alert.viewErrorMessage("Image type not valid .. ! \nThe valid types : JPEG - JPG - PNG");
            Logger.getLogger(Add_EditStudentUI.class).error(ex);
        } catch (HeadlessException ex){
            Alert.viewErrorMessage("You didn't select any file");
            Logger.getLogger(Add_EditStudentUI.class).error(ex);
        } catch (java.lang.NullPointerException ex){
            Logger.getLogger(Add_EditStudentUI.class).error(ex);
        }
    }//GEN-LAST:event_photoActionPerformed

    private void birthMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthMonthActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_EditStudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_EditStudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_EditStudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_EditStudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_EditStudentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.JComboBox admissionDay;
    private javax.swing.JComboBox admissionMonth;
    private javax.swing.JComboBox admissionYear;
    private javax.swing.JComboBox birthDay;
    private javax.swing.JComboBox birthMonth;
    private javax.swing.JComboBox birthYear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton close1;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JTextField first_name;
    private javax.swing.JTextField guadian_name;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField last_name;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JTextField middle_name;
    private javax.swing.JTextArea notes;
    private javax.swing.JTextField phone;
    private javax.swing.JButton photo;
    private javax.swing.JComboBox stage;
    private javax.swing.JTextField std_id;
    private javax.swing.JLabel studentPic;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
