package school.management.ui;

import java.io.File;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import school.management.Alert;
import school.management.Students;
import school.management.StudentsController;
import school.management.Subjects;
/**
 *
 * @author ahmed
 */
public class StudentsProfileUI extends javax.swing.JFrame {

    private ArrayList<Subjects> subjects;
    public StudentsProfileUI(Students student) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        Header header = new Header(this,jPanel1);
        header.setTitle("Students","icons\\icons8_Student_Male_100px_1.png");
        header.setBackTo(new StudentsUI());
        
        std_id.setText(student.getId().toString());
        String name = student.getFirstName() + " " + student.getMiddleName() + " " + student.getLastName();
        fullName.setText(name);
        int g = student.getGender();
        if (g == 0) {
            gender.setText("Male");
        } else {
            gender.setText("Female");
        }
        birthday.setText(student.getBirthday());
        admssion.setText(student.getAdmissionDate());
        stage.setText(student.getEducationStage().toString());
        guadianName.setText(student.getGuardianName());
        address.setText(student.getAddress());
        phone.setText(student.getPhone());
        notes.setText(student.getNotes());
        grade.setSelectedIndex(student.getEducationStage() - 1);
        setSubjectsIntoTable();
        
        File check = new File("image\\pp_"+std_id.getText()+".jpg");
        if (check.exists()) {
            pic.setIcon(new javax.swing.ImageIcon(check.getAbsolutePath()));
        } else {
            pic.setIcon(new javax.swing.ImageIcon("image\\student.png"));
        }
    }
    
    
    private DefaultTableModel getStudentSubjectsTable(ArrayList<Subjects> subs) {
        String[] columnNames = {"Subject", "First Month","Second Month","Third Month", "Midterm","Final","Total"};
        DefaultTableModel dtm = new DefaultTableModel(columnNames , 0);

        dtm.setColumnCount(7);
        for(Subjects s : subs) {
            dtm.addRow(new Object[] {
                s.getSub_name(),
                s.getFirst_month(),
                s.getSecond_month(),
                s.getThird_month(),
                s.getMidterm(),
                s.getFinalExam(),
                0
            });
        }
        
        return dtm;
    }
    
    
    private void setSubjectsIntoTable(){
        subjects = StudentsController.getStudentSubsByID(Integer.parseInt(std_id.getText()),
                                                                                grade.getSelectedIndex()+1,
                                                                                semester.getSelectedIndex()+1);
        subjectsTable.setModel(getStudentSubjectsTable(subjects));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        notes = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        std_id = new javax.swing.JLabel();
        fullName = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        guadianName = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        admssion = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        stage = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectsTable = new javax.swing.JTable();
        first_month = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        second_month = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        third_month = new javax.swing.JTextField();
        midterm = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        finalExam = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        grade = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        semester = new javax.swing.JComboBox();
        update = new javax.swing.JButton();
        refresh = new javax.swing.JLabel();
        createSubject = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(150, 40, 27));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setText("Address : ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setText("Student ID : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setText("Full Name : ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setText("Gender : ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setText("Birthday : ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setText("Notes : ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setText("Student Picture :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setText("Phone number : ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        notes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        notes.setText("Test");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(notes)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(notes)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 310, 190));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel10.setText("Admssions date : ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        pic.setBackground(new java.awt.Color(0, 0, 0));
        pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 250, 250));

        std_id.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        std_id.setText("Test");
        jPanel2.add(std_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        fullName.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        fullName.setText("Test");
        jPanel2.add(fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        gender.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        gender.setText("Test");
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        birthday.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        birthday.setText("Test");
        jPanel2.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        guadianName.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        guadianName.setText("Test");
        jPanel2.add(guadianName, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, -1, -1));

        address.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        address.setText("Test");
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, -1, -1));

        admssion.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        admssion.setText("Test");
        jPanel2.add(admssion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        phone.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        phone.setText("Test");
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, -1));

        stage.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        stage.setText("Test");
        jPanel2.add(stage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel20.setText("Education stage : ");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 20, 530));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel11.setText("Guadian name : ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));

        edit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel2.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 300, 40));

        jTabbedPane2.addTab("Student Information", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subjectsTable.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        subjectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        subjectsTable.setRowHeight(30);
        subjectsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subjectsTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 960, 270));

        first_month.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        first_month.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        first_month.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(first_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 80, 35));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Grade  :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 35));

        second_month.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        second_month.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        second_month.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(second_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 80, 35));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Second month :");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 100, 35));

        third_month.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        third_month.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        third_month.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(third_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 80, 35));

        midterm.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        midterm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        midterm.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(midterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 80, 35));

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setText("Midterm :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, 35));

        finalExam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        finalExam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        finalExam.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(finalExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 80, 35));

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setText("Final :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, 35));

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel18.setText("First month :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 35));

        grade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6" }));
        grade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeMouseClicked(evt);
            }
        });
        grade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gradeItemStateChanged(evt);
            }
        });
        grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeActionPerformed(evt);
            }
        });
        jPanel3.add(grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 90, 35));

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel19.setText("Semester :");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, 35));

        semester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First semester", "Second semester" }));
        semester.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                semesterMouseClicked(evt);
            }
        });
        semester.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                semesterItemStateChanged(evt);
            }
        });
        semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterActionPerformed(evt);
            }
        });
        jPanel3.add(semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 150, 35));

        update.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        update.setText("UPDATE MARKS");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 250, 40));

        refresh.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\School Management\\icons\\icons8_Refresh_50px.png")); // NOI18N
        refresh.setToolTipText("refresh table");
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });
        jPanel3.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, -1, -1));

        createSubject.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        createSubject.setText("CREATE SUBJECTS IN DATABASE");
        createSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSubjectActionPerformed(evt);
            }
        });
        jPanel3.add(createSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, 290, 40));

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel21.setText("Third month :");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, -1, 35));

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("THIS IS FOR NEW STUDENTS ONLY *");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, 35));

        jTabbedPane2.addTab("Subjects", jPanel3);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 980, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
            Add_EditStudentUI student = new Add_EditStudentUI();
            student.setVisible(true);
            student.setInputs(StudentsController.getStudentByID(std_id.getText()));
        } catch (Exception ex) {
            Alert.viewErrorMessage("There's an error");
            Logger.getLogger(StudentsProfileUI.class).error(ex);
        }
    }//GEN-LAST:event_editActionPerformed

    private void gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeActionPerformed

    private void semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        Subjects sub = subjects.get(subjectsTable.getSelectedRow());
        sub.setFirst_month(Integer.parseInt(first_month.getText()));
        sub.setSecond_month(Integer.parseInt(second_month.getText()));
        sub.setThird_month(Integer.parseInt(third_month.getText()));
        sub.setMidterm(Integer.parseInt(midterm.getText()));
        sub.setFinalExam(Integer.parseInt(finalExam.getText()));
        StudentsController.studentSubMarksUpdate(Integer.parseInt(std_id.getText()),
                                                                    grade.getSelectedIndex()+1,
                                                                    semester.getSelectedIndex()+1,
                                                                    sub);
    }//GEN-LAST:event_updateActionPerformed

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        setSubjectsIntoTable();
    }//GEN-LAST:event_refreshMouseClicked

    private void createSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSubjectActionPerformed
        StudentsController.setStudentSubjects(Integer.parseInt(std_id.getText()),grade.getSelectedIndex()+1);
    }//GEN-LAST:event_createSubjectActionPerformed

    private void semesterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semesterMouseClicked
        
    }//GEN-LAST:event_semesterMouseClicked

    private void gradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeMouseClicked
        
    }//GEN-LAST:event_gradeMouseClicked

    private void gradeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gradeItemStateChanged
        setSubjectsIntoTable();
    }//GEN-LAST:event_gradeItemStateChanged

    private void semesterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_semesterItemStateChanged
        setSubjectsIntoTable();
    }//GEN-LAST:event_semesterItemStateChanged

    private void subjectsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectsTableMouseClicked
        first_month.setText(subjectsTable.getModel().getValueAt(subjectsTable.getSelectedRow(), 1).toString());
        second_month.setText(subjectsTable.getModel().getValueAt(subjectsTable.getSelectedRow(), 2).toString());
        third_month.setText(subjectsTable.getModel().getValueAt(subjectsTable.getSelectedRow(), 3).toString());
        midterm.setText(subjectsTable.getModel().getValueAt(subjectsTable.getSelectedRow(), 4).toString());
        finalExam.setText(subjectsTable.getModel().getValueAt(subjectsTable.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_subjectsTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsProfileUI(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel admssion;
    private javax.swing.JLabel birthday;
    private javax.swing.JButton createSubject;
    private javax.swing.JButton edit;
    private javax.swing.JTextField finalExam;
    private javax.swing.JTextField first_month;
    private javax.swing.JLabel fullName;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox grade;
    private javax.swing.JLabel guadianName;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField midterm;
    private javax.swing.JLabel notes;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel refresh;
    private javax.swing.JTextField second_month;
    private javax.swing.JComboBox semester;
    private javax.swing.JLabel stage;
    private javax.swing.JLabel std_id;
    private javax.swing.JTable subjectsTable;
    private javax.swing.JTextField third_month;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
